main: com.sereneoasis.SereneRPG
name: SereneRPG
author: Sakrajin
version: 1.0.0
api-version: '1.20'
depend: [NDatabase]
load: STARTUP
commands:
  sereneRPG:
    description: Your description
    usage: /<command>